### ISSUE TITLE
Authorization has been denied for this request.

### ISSUE THREAD

**Issue by jeremy-holt** [abergs/OwinFriendlyExceptions#5]
How do you go about trapping errors set by OAuthGrantResourceOwnerCredentialsContext context.SetContext()?

Specifically I need to trap "Authorization has been denied for this request" in order to translate it into Portuguese before it gets back to the client.
Many thanks,
Jeremy

**Comment by abergs** [comment]
Could you expand a bit more about the `OAuthGrantResourceOwnerCredentialsContext context.SetContext()` part please? Where does this code run? 

Does SetContext throw the exception or does it write the response onto the HTTP stream itself?

**Comment by abergs** [comment]
Closing this issue for now
