### ISSUE TITLE
Map other exceptions

### ISSUE THREAD

**Issue by semack** [abergs/OwinFriendlyExceptions#9]
#Hi,

First of all I would like to say Thank You to the author for the great work he does.

I have a question. Is it possible to add a method like to ITransfromsMap.MapOthers(), it means map all other exceptions and handle them there?

Merry Christmas and Happy New Year =)
Andriy

**Comment by semack** [comment]
@abergs, anybody home? =)

**Comment by semack** [comment]
@abergs ?

**Comment by abergs** [comment]
Hey @semack. Sorry for missing this! Thank you a lot for your engagement and the PR. I like it, but I think we should make it a bit more obvious what MapOthers will do. `MapAllOthers` would maybe be a better terminology?

Could you also add a small README documentation, include a small example and a description with when/why I would use this? E.g: If you want to map all other exceptions in to a specific formatter, you can use the MapAllOthers to certain response, like this: CODE EXAMPLE.

**Comment by semack** [comment]
Hi @abergs ,

Thank you for the response. 

MapAllOthers is Ok, sorry for my ugly English ;)

I think this method has sense when you need to map all other exceptions to a **known** model. Please look on code example below:

```cs
private static ITransformsCollection GetExceptionConfiguration()
        {
            return TransformsCollectionBuilder.Begin()
                
                .Map<DbEntityValidationException>()
                .To(HttpStatusCode.BadRequest, "Entity Framework validation exception", ex =>
                {
                    var list = (from validationErrors in ex.EntityValidationErrors
                            from validationError in validationErrors.ValidationErrors
                            select
                            $"Class: {validationErrors.Entry.Entity.GetType().FullName}, Property: {validationError.PropertyName}, Error: {validationError.ErrorMessage}")
                        .ToList();

                    var response = new ErrorResponseModel
                    {
                        Message = ex.Message,
                        Exceptions = list
                    };
                    return response.ToJson();
                })
                
                .Map<ItemNotFoundException>()
                .To(HttpStatusCode.BadRequest, "Item not found", ex =>
                {
                    var response = new ErrorResponseModel(ErrorEnum.ItemNotFound);
                    return response.ToJson();
                })               
                
                .MapAllOthers()
                .To(HttpStatusCode.InternalServerError, "Internal Server Error", ex =>
                {
                    var response = new ErrorResponseModel
                    {
                        Message = ex.Message,
                        Exceptions = ex.GetInnerExceptions().Select(s => s.Message)
                    };
                    return response.ToJson();
                })

                .Done();
        }
```

**Comment by abergs** [comment]
Very nice, merged the PR! Great work and I'm really happy to see people giving back  and improving :)

**Comment by semack** [comment]
Could you update nuget packages?

**Comment by abergs** [comment]
@semack Oh yes, crap, I forgot about them. Need to check that out, will try to fix it during the evening

**Comment by semack** [comment]
Sounds good,  thanks!

**Comment by abergs** [comment]
published @semack
